In [1]:
import numpy as np

In [3]:
sigma = np.array([0.01, 0.02, 0.04, 0.06])
x = np.array([1.11, 1.17, 1.19, 1.23])
Kx = np.diag(sigma ** 2)

In [4]:
Kx

array([[0.0001, 0.    , 0.    , 0.    ],
       [0.    , 0.0004, 0.    , 0.    ],
       [0.    , 0.    , 0.0016, 0.    ],
       [0.    , 0.    , 0.    , 0.0036]])

In [8]:
sigma_1_sum = np.sum(1 / sigma ** 2)

In [9]:
sigma_1_sum

np.float64(13402.777777777777)

In [10]:
W = (1 / sigma ** 2) / sigma_1_sum

In [11]:
W

array([0.74611399, 0.1865285 , 0.04663212, 0.02072539])

In [12]:
Wx = W * x

In [13]:
Wx

array([0.82818653, 0.21823834, 0.05549223, 0.02549223])

In [14]:
np.sum(Wx)

np.float64(1.1274093264248706)

In [15]:
1 / sigma_1_sum

np.float64(7.461139896373058e-05)

In [16]:
r12 = -0.76
Kx[0, 1] = r12 * sigma[0] * sigma[1]
Kx[1, 0] = r12 * sigma[1] * sigma[0]

In [17]:
Kx

array([[ 0.0001  , -0.000152,  0.      ,  0.      ],
       [-0.000152,  0.0004  ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.0016  ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.0036  ]])

In [18]:
Kx_1 = np.linalg.inv(Kx)

In [19]:
Kx_1

array([[23674.24242424,  8996.21212121,    -0.        ,    -0.        ],
       [ 8996.21212121,  5918.56060606,     0.        ,     0.        ],
       [    0.        ,     0.        ,   625.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ,   277.77777778]])

In [20]:
ones = np.ones(Kx_1.shape[0])

In [21]:
ones

array([1., 1., 1., 1.])

In [23]:
(Kx_1 @ ones) @ ones

np.float64(48488.00505050504)

In [24]:
x_ob = ((Kx_1 @ ones) @ x) / ((Kx_1 @ ones) @ ones)

In [25]:
x_ob

np.float64(1.1301744678080852)

In [27]:
1 / ((Kx_1 @ ones) @ ones)

np.float64(2.062365731397696e-05)

In [28]:
np.sqrt(1 / ((Kx_1 @ ones) @ ones))

np.float64(0.004541327703874381)

In [29]:
np.sqrt(1 / sigma_1_sum)

np.float64(0.008637789008984334)